#!/usr/bin/with-contenv bash

echo "******* This script has been deprecated and will be removed in a future version. In order to add peers, change the PEERS env var and recreate your container. Existing peers will still use the same private and public keys. *******"

if [ ! -f /home/cuong/config/wg0.conf ] || [ -z "$PEERS" ]; then
  echo "Wireguard is not set up in server mode"
  exit 0
fi

INTERNAL_SUBNET=${INTERNAL_SUBNET:-10.13.13.0}
INTERFACE=$(echo "$INTERNAL_SUBNET" | awk 'BEGIN{FS=OFS="."} NF--')
if [ -z "$SERVERURL" ] || [ "$SERVERURL" = "auto" ]; then
  SERVERURL=$(curl icanhazip.com)
fi
SERVERPORT=${SERVERPORT:-51820}
if [ -z "$PEERDNS" ] || [ "$PEERDNS" = "auto" ]; then
  PEERDNS="${INTERFACE}.1"
fi

for i in {1..254}; do
  if grep -q "AllowedIPs = ${INTERFACE}.$(( $i + 1 ))/32" /home/cuong/config/wg0.conf; then
    echo "Peer $i exists"
  else
    echo "Adding new Peer $i"
    mkdir -p /home/cuong/config/peer${i}
    if [ ! -f /home/cuong/config/peer${i}/privatekey-peer${i} ]; then
      umask 077
      wg genkey | tee /home/cuong/config/peer${i}/privatekey-peer${i} | wg pubkey > /home/cuong/config/peer${i}/publickey-peer${i}
    fi
    eval "`printf %s`
    cat <<DUDE > /home/cuong/config/peer${i}/peer${i}.conf
`cat /home/cuong/config/templates/peer.conf`
DUDE"
    cat <<DUDE >> /home/cuong/config/wg0.conf
[Peer]
PublicKey = $(cat /home/cuong/config/peer${i}/publickey-peer${i})
AllowedIPs = ${INTERFACE}.$(( $i + 1 ))/32

DUDE
    echo "PEER ${i} QR code:"
    qrencode -t ansiutf8 < /home/cuong/config/peer${i}/peer${i}.conf
    qrencode -o /home/cuong/config/peer${i}/peer${i}.png < /home/cuong/config/peer${i}/peer${i}.conf
    chown -R abc:abc /home/cuong/config/peer${i}
    s6-svc -t /var/run/s6/services/wireguard
    break
  fi
done
